### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by neckaros** [FWeinb/rclone-js#1]
Hello,
Thanks for this great library.
i'm encoutering the following stack on NodeJS  v8.5.0: 
```
ReferenceError: atob is not defined
    at base64 (c:\Devs\rs-api\node_modules\rclone\dist\reveal.js:53:3)
    at reveal (c:\Devs\rs-api\node_modules\rclone\dist\reveal.js:32:15)
    at generateKeys (c:\Devs\rs-api\node_modules\rclone\dist\rclone.js:60:37)
    at c:\Devs\rs-api\node_modules\rclone\dist\rclone.js:28:7
    at Promise (<anonymous>)
    at Rclone (c:\Devs\rs-api\node_modules\rclone\dist\rclone.js:23:10)
    at Object.Rclone (c:\Devs\rs-api\node_modules\rclone\dist\index.js:21:29)
```

**Comment by neckaros** [comment]
Adding those lines at the begining of reveal.js:
if (typeof atob === 'undefined') {
  global.atob = function (b64Encoded) {
    return new Buffer(b64Encoded, 'base64').toString('binary');
  };
}
solved the issue

**Comment by FWeinb** [comment]
Yeah running it on node was not my first priority. Thanks for reporting and suggesting a fix.
